services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: weatherapp_backend
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=9000
      - MAP_ENDPOINT=http://api.openweathermap.org/data/2.5
      - TARGET_CITY=Warsaw,pl
    volumes:
      # Mount source code for hot reload in development
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      # Exclude node_modules from host
      - /app/node_modules
    networks:
      - weatherapp-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weatherapp_frontend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - ENDPOINT=http://backend:9000
    volumes:
      # Mount source code for hot reload in development
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/webpack.config.js:/app/webpack.config.js
      # Exclude node_modules from host
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - weatherapp-network
    restart: unless-stopped

networks:
   weatherapp-network:
     driver: bridge
