
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: weatherapp_backend
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=9000
      - MAP_ENDPOINT=http://api.openweathermap.org/data/2.5
      - TARGET_CITY=Madrid,es
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - /app/node_modules
    networks:
      - weatherapp-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: weatherapp_frontend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - ENDPOINT=http://backend:9000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/webpack.config.js:/app/webpack.config.js
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - weatherapp-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: weatherapp_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
    depends_on:
      - frontend
      - backend
    networks:
      - weatherapp-network
    restart: unless-stopped
    
networks:
  weatherapp-network:
    driver: bridge

